### ISSUE TITLE
Pixfont can't write text on image

### ISSUE THREAD

**Issue by ErfanAkbarimanesh** [pbnjay/pixfont#1]
Hello i work with your package and test it for write text on image but it can't 
Please check this link(mysource code here) :  
https://gist.github.com/anonymous/ad44212595ad1155f2ee

**Comment by pbnjay** [comment]
You need to include at least your input and output files if you want me to
debug your code for free.

**Comment by pbnjay** [comment]
No response so I'm assuming you found the issue. Cheers!
