### ISSUE TITLE
simply spacing characters neatly kinda impossible

### ISSUE THREAD

**Issue by splace** [pbnjay/pixfont#11]
most chars have an empty column of pixels on the right hand size, but many, unknown, do not.

builtin margin on right...
![2b](https://github.com/pbnjay/pixfont/assets/1234848/9385f146-6b7c-4962-9102-309da05a552e)
no margin...
![2a](https://github.com/pbnjay/pixfont/assets/1234848/d0a92992-2976-492a-a392-fdc08d7ef10c)

**Comment by pbnjay** [comment]
That is pretty much inherent to pixel fonts, the best solution using this package is the “variable width” setting mentioned in the readme.

**Comment by splace** [comment]
i was expecting either just joining the images or joining with a gap. wasn't interested in messing with v.width, so didn't read.
