### ISSUE TITLE
8x8 font is drawn as 9x8

### ISSUE THREAD

**Issue by udhos** [pbnjay/pixfont#2]
I noticed pixfont.DrawString() draws the 8x8 font in 9x8 cells.

Is there an option to render the 8x8 font with 8-pixel width instead of 9-pixel width?

I am using the 8x8 font to create an atlas for opengl text rendering in an experimental Android game: https://github.com/udhos/fugo/blob/master/demo/invader/font.go

I think 8x8 cells would deliver a more realistic look for such a classic font. :)

**Comment by pbnjay** [comment]
I added a package-level var so you can do this using `pixfont.Spacing=0` somewhere in your setup code. For simple stuff like this feel free to submit a PR in the future. Cheers!

**Comment by udhos** [comment]
It worked! Thanks!!
